### ISSUE TITLE
One graphical issue and suggestion

### ISSUE THREAD

**Issue by Pyroman2xxx** [zeel01/MonsterBlocks#10]
Created a drow mage and MonsterBlocks seems to have issues with having both Innate spells and regular spells at the same time when rendering:
![Annotation 2020-08-29 232711](https://user-images.githubusercontent.com/67874836/91650573-42aa6280-ea4f-11ea-9029-35d2b346aa5e.png)

Also, it would be very helpful if the spell slots reflected how many were left rather than max.

Thank you for this mod!

**Comment by zeel01** [comment]
The display issue *should* be fixed in v2.x.

The other thing is a side effect of the sheet being a read-only reference: Only max slots matter if it's just static info like a book. 

However, 2.x changes all that. The beta is already available if you want to check it out, this and many more things have changed to make the sheet fully-featured.
