### ISSUE TITLE
Make the saves/skill roll menus optional, or at least not triggered on hover.

### ISSUE THREAD

**Issue by Pyroman2xxx** [zeel01/MonsterBlocks#14]
Would you be able to make the Saving Throws and Skill check drop-downs an optional setting?

The drop-downs are getting in the way of the listed Proficient Skills since the drop-down appears as soon as I hover over any of the Skills or Saves. I neither want nor need the ability to roll non-proficient skills and saves since they are essentially raw ability checks.

Thank you!

**Comment by zeel01** [comment]
This was a highly requested feature (rolling any saves/skills), since due to automation just rolling a raw ability check won't cut it. But obviously this isn't needed for everyone (I don't even use it). I can add a toggle for it, though I'm not 100% sure that's the best option. I might switch it to a click-on/click-off menu like the edit/add menus, would that seem sufficient? This would effect clicking the words "Skills" or "Saving Throws".

**Comment by Pyroman2xxx** [comment]
> I might switch it to a click-on/click-off menu like the edit/add menus, would that seem sufficient?

That works. Anything that keeps it from expanding on mouseover when I am trying to click the listed skills.

**Comment by zeel01** [comment]
Changed to click-on/click-off in the next release.
