### ISSUE TITLE
stats block theme doesn't apply with "Ernie's Modern UI" module

### ISSUE THREAD

**Issue by PalaNolho** [zeel01/MonsterBlocks#165]
Hi, 
The status blocks themes don't seem to work with the [Ernie's Modern UI](https://foundryvtt.com/packages/ernies-modern-layout). Some parts of the theme seem to be applied but not all and not for all the themes.

- The themes and backgrounds don't apply (however the text style seems to apply and the description "hover tooltip" seems to render correctly too)
- The Settings cog is also not usable because it is under the monster name(?) and clicking on it starts editing the name.
- The sheet doesn't also show in "wide mode" when using this module. Instead, it will show slim (as in the screenshot) and you have to scroll down.

It would be great if your themes would be able to override everything else AND have an option to not apply any theme so that any other theme in use could take effect.

![image](https://user-images.githubusercontent.com/6009914/156542092-463c4b3d-a679-4915-a3bc-811bdb67a250.png)

**Comment by zeel01** [comment]
Unfortunately this is a problem with the UI theme, not with Monster Blocks. Any module that applies changes to CSS across the entire Foundry application will likely cause some conflicts with some modules, and it isn't possible for modules to adapt to all of these changes. CSS is a top-down thing, styles applied "above" the module cascade down into it. The only way to avoid them, is to explicitly contradict them - but that not only means maintaining a lot of extra code, but it could cause issues with *other* modules, or lead to issues when the UI theme *isn't* enabled.

There are two options for resolving the conflict. The best is for the UI theme to be adjusted such that it doesn't effect applications with the class `.monsterblock` on them, or ideally so that it only effects the applications that its designer specifically knows will work with it. Considering that I see a list of compatible modules on their Github readme, they may be open to making changes that ensure compatibility.

The other option is to use the [Custom CSS](https://foundryvtt.com/packages/custom-css) module to create local overrides for the styles that conflict.
