### ISSUE TITLE
Loading certain maps lags seemingly due to Monster Blocks.

### ISSUE THREAD

**Issue by mkampus** [zeel01/MonsterBlocks#17]
Basically, there's a long lag when loading certain maps, seemingly without reason. No combat going on, no tokens on the maps, no iniative.. nothing.

`DevTools failed to load SourceMap: Could not load content for "DOMAINADDRESS"/modules/monsterblock/input-expressions/math.min.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`

**Comment by zeel01** [comment]
The message is caused by Devtools looking for a source map for the minified Math.js code. This is because you have source maps enabled as a dev feature.

Im not sure why this would cause a slowdown, but the solution would be to disable source maps when not using them.

To verify the issue, try disabling source maps and see if the slowdown goes away. If it doesn't, there is probably a different issue at play.
