### ISSUE TITLE
Request, Honor and Sanity skill check disabling for npc's

### ISSUE THREAD

**Issue by maxobremer** [zeel01/MonsterBlocks#209]
It would be nice if you could hide the honor and sanity skills for just npc's since they might only be relevant to players.

**Comment by zeel01** [comment]
Honestly didn't even realize that this was implemented in the system. But looking at it, even with both enabled I don't see a significant negative impact. The ability score row is a _little_ cramped sure, but it's not terrible. That being said, if you find it annoying I would recommend installing the Custom CSS module https://foundryvtt.com/packages/custom-css and adding the following styles:

```css
.monsterblock .ability[data-ability=san],
.monsterblock .ability[data-ability=hon]
{
	display: none;
}
```

This will hide the Sanity and Honor scores from the Monster Blocks sheet. You could even go so far as to use the "custom" field under the them menu to individually assign specific NPCs to a theme that hides these or not.

As for adding a feature into the module, there are already a lot of settings and the more there are the more effort it becomes to maintain. And since the majority of users don't use those scores, and those who do likely don't mind them showing on the NPC sheet, I don't think it's something I can devote time to at the moment (I'm having a hard time keeping it up to date with Core and dnd5e). I hate to say "no" on stuff like this, but the alternative is leaving the issue in the backlog indefinitely.
