### ISSUE TITLE
Make rolling to recharge also set the charged flag on the item.

### ISSUE THREAD

**Issue by InnilToo** [zeel01/MonsterBlocks#23]
Hello,
I've encountered a problem with Recharge on monster abilities like Fire Breath. It works as intended on the default 5e NPC Sheet. But when I roll for the charge on Monster Blocks and get success, it says I have no available uses remaining. I am confident I have the right setting since it works as I would expect on the default sheet.

![image](https://user-images.githubusercontent.com/33260912/97776492-d7712f80-1b68-11eb-8f5e-d6aed9d100ba.png)
![image](https://user-images.githubusercontent.com/33260912/97776541-4ea6c380-1b69-11eb-91cb-d89f68c724a4.png)
![image](https://user-images.githubusercontent.com/33260912/97776561-6d0cbf00-1b69-11eb-9550-4b89bfaaa9e7.png)

**Comment by zeel01** [comment]
This *technically* works as intended. The recharge roll is a "quick roll" on the sheet, rather than a normal item roll, so all it does is roll the dice, and in this case indicate whether or not the roll was high enough.

This was a feature I added for low-automation play, it doesn't actually respect the "charged" checkmark in the item, it assumes that the GM remembers whether or not the ability was charged, it just rolls a d6 when requested and doesn't modify any underlying data. 

Clearly that's not how everyone plays, and also a little confusing. There isn't really any harm in it if it *did* actually recharge the ability. I'll add this suggestion to my list.

**Comment by figotech** [comment]
I also would expect the charge rolling to recharge the action if it rolls high enough, after all its the behaviour of the default sheet.

A mod like Token hud for example will roll de d6 if not charged and mark it as (charged) if succesfull or roll the attack if charged, all from the same "link".  Also if possible if an attack is a cahrge on 6 could it show (Recharge 6) instead of (Recharge 6-6)?

**Comment by zeel01** [comment]
This should work as expected in the next release.
