### ISSUE TITLE
Sheet does not resize correctly in Firefox. 

### ISSUE THREAD

**Issue by iDvoth** [zeel01/MonsterBlocks#24]
![image](https://user-images.githubusercontent.com/65934484/97791923-268d8380-1bae-11eb-9687-ea7936e7c718.png)
For whatever reason the sheet always appear like this (stuck out of reach), also I can't seem to change it's size. This is a clean campaign with no other mods turned on.

**Comment by iDvoth** [comment]
I just noticed that the resize thing is by design, but still it's always significantly to tall for my screen resolution and well it get stuck at the top too.

**Comment by zeel01** [comment]
It is not resizable.
The issue here is that the automatic sizing is not working correctly. This is a known issue in Fielrefox, so I'm assuming you are using Firefox? 

Due to less powerful dev tools in Firefox, I haven't yet been able to determine the issue/whether or not it's possible for it to work correctly in Firefox.

However, it works in Chrome and the app.

**Comment by iDvoth** [comment]
Oh, you are right, it's a Firefox issue. Should've known to test other browsers...

**Comment by zeel01** [comment]
I'll keep this open as a reminder to continue to work on this issue.

**Comment by figotech** [comment]
I remember that previously the module: "Popout resizer" would work with monsterblocks and allow to resize the window without any trouble, that could help.  Also using the module Popout! you can get it into a new window in firefox and resize that one which is helpful if you want to use Firefox

**Comment by Varriount** [comment]
I've been doing a bit of digging into this. My current suspicions are on the initial height differences in Firefox and Chrome causing getClientBoundingRect to return different values.

**Comment by zeel01** [comment]
Thanks to @Varriount, the issue has been found. In Firefox there is a weird behavior with Flexbox wherein it doesn't respect overflows. Since I'm not even using flexbox, I didn't even think to look there for issues. But *Core* is using flexbox, and sure enough one of the containers `.window-content` is `display: flex;` in Core. Overriding that to `display: block;` magically fixes the issue, and window sizing works as expected.

So this issue should finally be resolved in the next release!
