### ISSUE TITLE
Make CSS code to show only icons on header buttons an option in module settings or cog-menu

### ISSUE THREAD

**Issue by DipsoNOR** [zeel01/MonsterBlocks#46]
With more modules adding buttons to the top bar of windows (like the new tokenizer preview from VTTA for instance) its getting really crowded up there, and since monster blocks are usually pretty narrow, any overflowing buttons simply disappear. (Because, I assume, foundry has no overflow logic for these buttons) 

Currently I'm using stylish to apply the following code:

`.window-app.monsterblock .window-header {
    font-size: 0px;
    padding-right: 30px;
}
.window-app.monsterblock .window-header i {
    font-size: 14px;
}`

I think it would be nice if this was an option either in the module settings or in the "cogwheel menu" in monsterblocks, for users less knowledgeable about CSS or users not wanting to run yet another extension to modify the CSS.

**Comment by zeel01** [comment]
Not saying no, but you *can* already use the compact window mode for this.

Also, you can use the Custom CSS module instead of Stylish, I find stylish sometimes gives me issues. 

I will consider adding an option for just this though.

**Comment by DipsoNOR** [comment]
> 
> 
> Not saying no, but you _can_ already use the compact window mode for this.
> 
> Also, you can use the Custom CSS module instead of Stylish, I find stylish sometimes gives me issues.
> 
> I will consider adding an option for just this though.

Fair enough. Just making a suggestion :)
To be honest core should have some sort of overflow function if modules keep adding buttons to windows :P

**Comment by zeel01** [comment]
After some consideration, I've decided I don't intend to add this as its own option. I feel like there are already getting to be too many options, and since the compact window option already includes this, I don't really want to add further granularity.

I have also seen some issues on the Core repo regarding this problem (too many header buttons), so we may be seeing this actually *fixed* in the 0.8.x series anyway.
