### ISSUE TITLE
[Feature Request] Expand Biography Section

### ISSUE THREAD

**Issue by jeremyregnerus** [zeel01/MonsterBlocks#51]
Allow for the Biography section / page to expand in order to show more content. Similar to how the "front" of the character sheet expands when there is more content added.

**Comment by zeel01** [comment]
So this one is a bit tricky. This was actually the original way I tried to implement the feature, the whole bio would just display as columns like the rest of the statblock. The problem is, the bio is edited using the rich text TinyMCE editor. There isn't a way to make the editor display in a reasonable way, so there was some incredibly janky UI if you clicked edit.

I tried a number of things, but in the end the only good option that allowed the UI to be consistent was what we have now. Plus, bios can be *very long* and as columns on the sheet, this can result in a window that's too big to use - something *has* to scroll, but scrolling totally messes up the way the rest of the sheet layout works.

So in the end, the only thing that worked in a way that didn't basically suck, was what I have implemented now. It's sadly not as pretty as I would like, but it functions as needed and doesn't result in bizarre UI behavior.
