### ISSUE TITLE
Biography improvements

### ISSUE THREAD

**Issue by figotech** [zeel01/MonsterBlocks#57]
So I've been giving a lot of thought to the way biography works.

Essentially the big problem is that if you click on a compendium monster, since the biography is a flag that reloads its really cumbersome to check it.

Now I assume this is because of the way you need to create the window itself, since a big sheet (like an adult dragon) will be large horizontaly and we all know we kinda need the single column for the bio window.

So what I think could work is.... The bio should be a new window!!  I would definitely would create both window objects on render (so everything would load at once when checking a compendium), then the bio option would just be a "show", the bio can be moved and closed by itself.  This is also I think overall better. Most of the time if I switch to bio is to check some details then to switch back to the monster sheet itself. This way you just close it or can even keep it there while rolling attacks.

And about maybe placing a link itself in the sheet... It could be a text that says Biography or Bio aligned right on the same row as the challenge rating, that line will never grow far to the right side. 

Anyway, just the ideas I had!

**Comment by zeel01** [comment]
This is a fairly unlikely solution I'm afraid. Adding an additional window is a fairly substantial addition to the module, as another window would be another FormApplication independent of the sheet. It's certainly doable, but it expands the scope beyond what I'm really happy with. Plus, adding a new button to the sheet body is a definite no, the core goal of the sheet is to match the 5e statblock as best as possible, and there is really only one place that I'm willing to bend that slightly (hp being represented as a ratio instead of a single number).

This means either a new header button (not great), or a menu option which I don't think solves your use case well.

There is merit to the idea of a pop-out bio, but I don't think it fits this module. Instead, this might be a useful suggestion for a *new* module which could be made compatible with Monster Blocks or any other sheet easily. It could use a header button, or even a key binding to open the bio window.

There is a #package-ideas channel on the [ League of FVTT Devs Discord](https://discord.gg/83uJANRska). And we have a [Trello board](https://trello.com/invite/b/5neFnUv5/718e3751c9418c651807ceced750007f/systems) to track ideas.
