### ISSUE TITLE
At Will Innate Spellcasting

### ISSUE THREAD

**Issue by friction1** [zeel01/MonsterBlocks#70]
Monster blocks character sheets do not appear to auto generate clickable "at will" spells for monsters with Innate Spellcasting. It successfully auto generates clickable spells for 1/day or 3/day style spells.
<img width="852" alt="Screen Shot 2021-03-21 at 10 27 11 AM" src="https://user-images.githubusercontent.com/11384891/111908546-0d3b8580-8a30-11eb-95c3-fdfaf89587d1.png">

**Comment by zeel01** [comment]
IIRC, you need to set them to innate preparation mode, but without a limit on casting per day. This should show a row that says "at will" above the other rows. 

There is a conflict here, because "at will" spells for a prepared caster are a thing too, and they need to be distinguished.

Example: Archmage (SRD)
