### ISSUE TITLE
Compatibility with Input Expressions Module

### ISSUE THREAD

**Issue by ravingdragoon** [zeel01/MonsterBlocks#78]
When running Monster Blocks with Intput Expressions, I get the attached error, openable in Notepad ++, and Monster Blocks does not function properly.
[InputExpressionsError.zip](https://github.com/zeel01/MonsterBlocks/files/6586456/InputExpressionsError.zip)

**Comment by zeel01** [comment]
Please include the text of the error message in your issue, rather than attaching a zip file.

Also please include the version of Monster Blocks, Input Expressions, Foundry, and dnd5e on which you are experiencing the issue.

**Comment by ravingdragoon** [comment]
Putting this here in case it helps:

![image](https://user-images.githubusercontent.com/72875320/120707707-86fbe080-c46f-11eb-881d-e2c6c5c2d14b.png)
[ravingdragoon-lost-laboratory-of-kwalish.forge-vtt.com-162275128.txt](https://github.com/zeel01/MonsterBlocks/files/6594173/ravingdragoon-lost-laboratory-of-kwalish.forge-vtt.com-162275128.txt)

**Comment by zeel01** [comment]
The error message you are seeing does not indicate any actual problem, the two modules just share something. I should make it not do that, but it doesn't actually hurt anything.

This means that whatever isn't working in Monster Blocks is not related to that error. I need more information about what's not working in order to diagnose the problem.

Please specify what version of: Foundry, Monser Blocks, Input Expressions, and dnd5e you are currently using. Also specify any other details about what's going on, "Monster Blocks does not function properly" isn't enough information. Please describe what part isn't functioning.
