### ISSUE TITLE
Ability to Roll Saving Throws when not proficient

### ISSUE THREAD

**Issue by shinkei13** [zeel01/MonsterBlocks#8]
I was wondering if you could add the option to roll a Saving Throw from the ability modifier, in the case a monster is not proficient but still needs to roll to save. I understand that there are additional checks on the back-end where you're actually preventing the Default functionality, however I was thinking something like how you handle Item/Spell cards: Left Click for Ability Checks, Right Click for Saving Throws.

Occasionally I'll have an ability that situationally enhances a monster's Saving Throw, and something like this would make things more transparent.

**Comment by zeel01** [comment]
Yeah, it's something I would like to do. For most cases just rolling the ability check is sufficient, but if there is some automation applying for saves only, I get how it can be an issue.
I just have to decide on an the right interaction. I don't think I want to use right click, since that's "edit" for other stuff. And modifier keys conflict with stuff like Better Rolls that use them extensively.
I haven't decided the right route to take yet, I could easily just let the user reveal all saves with a switch, but I don't really like that option either.

**Comment by zeel01** [comment]
Now possible in the v2,0.0 Beta

[Manifest](https://raw.githubusercontent.com/zeel01/MonsterBlocks/v2.x/module.json)
